version: "3.9"
services:
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        command:
            redis-server
        networks:
            - webnet
    mongodb:
        image: mongo:5.0
        ports:
            - '27017:27017'
        networks:
            - webnet
    db:
        build: ./db/
        image: bhavan/transportation-db
        container_name: database
        ports:
            - 5003:5003
        links:
            - mongodb
        networks:
            - webnet
    backend:
        build: ./backend/
        image: bhavan/transportation-backend
        container_name: backend
        restart: always
        ports:
            - 5000:5000
        links:
            - mongodb
        networks:
            - webnet
    broker1:
        build: ./broker1/
        image: bhavan/transportation-broker1
        container_name: broker1
        restart: always
        ports:
            - 7001:7001
        depends_on:
            - redis
        environment:
            - redis-host=redis
        networks:
            - webnet
    broker2:
        build: ./broker2/
        image: bhavan/transportation-broker2
        container_name: broker2
        restart: always
        ports:
            - 7002:7002
        depends_on:
            - redis
        environment:
            - redis-host=redis
        networks:
            - webnet
    broker3:
        build: ./broker3/
        image: bhavan/transportation-broker3
        container_name: broker3
        restart: always
        ports:
            - 7003:7003
        depends_on:
            - redis
        environment:
            - redis-host=redis
        networks:
            - webnet
    publisher1:
        build: ./publisher1/
        image: bhavan/transportation-publisher1
        container_name: publisher1
        restart: always
        ports:
            - 6001:6001
        links:
            - mongodb
        networks:
            - webnet
    publisher2:
        build: ./publisher2/
        image: bhavan/transportation-publisher2
        container_name: publisher2
        restart: always
        ports:
            - 6002:6002
        links:
            - mongodb
        networks:
            - webnet
    publisher3:
        build: ./publisher3/
        image: bhavan/transportation-publisher3
        container_name: publisher3
        restart: always
        ports:
            - 6003:6003
        links:
            - mongodb
        networks:
            - webnet
    subscriber1:
        build: ./subscriber/
        image: bhavan/transportation-subscriber1
        container_name: subscriber1
        restart: always
        ports:
            - 9001:9001
        depends_on:
            - redis
        environment:
            - redis-host=redis
            - host=9001
        networks:
            - webnet
    subscriber2:
        build: ./subscriber/
        image: bhavan/transportation-subscriber2
        container_name: subscriber2
        restart: always
        ports:
            - 9002:9002
        depends_on:
            - redis
        environment:
            - redis-host=redis
            - host=9002
        networks:
            - webnet
    subscriber3:
        build: ./subscriber/
        image: bhavan/transportation-subscriber3
        container_name: subscriber3
        restart: always
        ports:
            - 9003:9003
        depends_on:
            - redis
        environment:
            - redis-host=redis
            - host=9003
        networks:
            - webnet
    frontend:
        build: ./client/
        image: bhavan/transportation-client
        container_name: frontend
        restart: always
        ports:
            - 8080:8080
        expose:
            - "8080"

networks:
    webnet:
        driver: bridge